version: '2'

services:
  identity.api:
    build:
      args:
        source: ${DOCKER_BUILD_SOURCE}
    volumes:
      - ~/clrdbg:/clrdbg:ro
    entrypoint: tail -f /dev/null
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"

  profile.api:
    build:
      args:
        source: ${DOCKER_BUILD_SOURCE}
    volumes:
      - ~/clrdbg:/clrdbg:ro
    entrypoint: tail -f /dev/null
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"

  projects.api:
    build:
      args:
        source: ${DOCKER_BUILD_SOURCE}
    volumes:
      - ~/clrdbg:/clrdbg:ro
    entrypoint: tail -f /dev/null
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"
